// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Bucket extends pulumi.CustomResource {
    /**
     * Get an existing Bucket resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Bucket {
        return new Bucket(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'supabase:v0:Bucket';

    /**
     * Returns true if the given object is an instance of Bucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bucket.__pulumiType;
    }

    public readonly allowed_mime_types!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly bucket_name!: pulumi.Output<string>;
    public readonly file_size_limit!: pulumi.Output<number | undefined>;
    public readonly name!: pulumi.Output<string | undefined>;
    public readonly project_ref!: pulumi.Output<string>;
    public readonly public!: pulumi.Output<boolean | undefined>;

    /**
     * Create a Bucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BucketArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.project_ref === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project_ref'");
            }
            resourceInputs["allowed_mime_types"] = args ? args.allowed_mime_types : undefined;
            resourceInputs["file_size_limit"] = args ? args.file_size_limit : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["project_ref"] = args ? args.project_ref : undefined;
            resourceInputs["public"] = args ? args.public : undefined;
            resourceInputs["bucket_name"] = undefined /*out*/;
        } else {
            resourceInputs["allowed_mime_types"] = undefined /*out*/;
            resourceInputs["bucket_name"] = undefined /*out*/;
            resourceInputs["file_size_limit"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["project_ref"] = undefined /*out*/;
            resourceInputs["public"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Bucket.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Bucket resource.
 */
export interface BucketArgs {
    allowed_mime_types?: pulumi.Input<pulumi.Input<string>[]>;
    file_size_limit?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    project_ref: pulumi.Input<string>;
    public?: pulumi.Input<boolean>;
}
