// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { DbFunctionArgs } from "./dbFunction";
export type DbFunction = import("./dbFunction").DbFunction;
export const DbFunction: typeof import("./dbFunction").DbFunction = null as any;
utilities.lazyLoad(exports, ["DbFunction"], () => require("./dbFunction"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "supabase:functions:DbFunction":
                return new DbFunction(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("supabase", "functions", _module)
