# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_supabase.config as __config
    config = __config
    import pulumi_supabase.functions as __functions
    functions = __functions
    import pulumi_supabase.organizations as __organizations
    organizations = __organizations
    import pulumi_supabase.projects as __projects
    projects = __projects
    import pulumi_supabase.secrets as __secrets
    secrets = __secrets
    import pulumi_supabase.storage as __storage
    storage = __storage
else:
    config = _utilities.lazy_import('pulumi_supabase.config')
    functions = _utilities.lazy_import('pulumi_supabase.functions')
    organizations = _utilities.lazy_import('pulumi_supabase.organizations')
    projects = _utilities.lazy_import('pulumi_supabase.projects')
    secrets = _utilities.lazy_import('pulumi_supabase.secrets')
    storage = _utilities.lazy_import('pulumi_supabase.storage')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "supabase",
  "mod": "functions",
  "fqn": "pulumi_supabase.functions",
  "classes": {
   "supabase:functions:DbFunction": "DbFunction"
  }
 },
 {
  "pkg": "supabase",
  "mod": "organizations",
  "fqn": "pulumi_supabase.organizations",
  "classes": {
   "supabase:organizations:Organization": "Organization"
  }
 },
 {
  "pkg": "supabase",
  "mod": "projects",
  "fqn": "pulumi_supabase.projects",
  "classes": {
   "supabase:projects:Project": "Project"
  }
 },
 {
  "pkg": "supabase",
  "mod": "secrets",
  "fqn": "pulumi_supabase.secrets",
  "classes": {
   "supabase:secrets:Secret": "Secret"
  }
 },
 {
  "pkg": "supabase",
  "mod": "storage",
  "fqn": "pulumi_supabase.storage",
  "classes": {
   "supabase:storage:Bucket": "Bucket"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "supabase",
  "token": "pulumi:providers:supabase",
  "fqn": "pulumi_supabase",
  "class": "Provider"
 }
]
"""
)
