# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_supabase.config as __config
    config = __config
    import pulumi_supabase.v0 as __v0
    v0 = __v0
    import pulumi_supabase.v1 as __v1
    v1 = __v1
else:
    config = _utilities.lazy_import('pulumi_supabase.config')
    v0 = _utilities.lazy_import('pulumi_supabase.v0')
    v1 = _utilities.lazy_import('pulumi_supabase.v1')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "supabase",
  "mod": "v0",
  "fqn": "pulumi_supabase.v0",
  "classes": {
   "supabase:v0:Bucket": "Bucket",
   "supabase:v0:Migration": "Migration",
   "supabase:v0:Organization": "Organization",
   "supabase:v0:Project": "Project"
  }
 },
 {
  "pkg": "supabase",
  "mod": "v1",
  "fqn": "pulumi_supabase.v1",
  "classes": {
   "supabase:v1:Organization": "Organization",
   "supabase:v1:Project": "Project",
   "supabase:v1:Secret": "Secret"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "supabase",
  "token": "pulumi:providers:supabase",
  "fqn": "pulumi_supabase",
  "class": "Provider"
 }
]
"""
)
