# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_supabase.config as __config
    config = __config
    import pulumi_supabase.supabase as __supabase
    supabase = __supabase
else:
    config = _utilities.lazy_import('pulumi_supabase.config')
    supabase = _utilities.lazy_import('pulumi_supabase.supabase')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "supabase",
  "mod": "supabase",
  "fqn": "pulumi_supabase.supabase",
  "classes": {
   "supabase:supabase:Bucket": "Bucket",
   "supabase:supabase:Migration": "Migration",
   "supabase:supabase:Organization": "Organization",
   "supabase:supabase:Project": "Project",
   "supabase:supabase:Secret": "Secret"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "supabase",
  "token": "pulumi:providers:supabase",
  "fqn": "pulumi_supabase",
  "class": "Provider"
 }
]
"""
)
