// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Supabase.Supabase
{
    [SupabaseResourceType("supabase:supabase:Migration")]
    public partial class Migration : global::Pulumi.CustomResource
    {
        [Output("db_password")]
        public Output<string> Db_password { get; private set; } = null!;

        [Output("include_all")]
        public Output<bool?> Include_all { get; private set; } = null!;

        [Output("include_roles")]
        public Output<bool?> Include_roles { get; private set; } = null!;

        [Output("include_seed")]
        public Output<bool?> Include_seed { get; private set; } = null!;

        [Output("project_id")]
        public Output<string> Project_id { get; private set; } = null!;


        /// <summary>
        /// Create a Migration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Migration(string name, MigrationArgs args, CustomResourceOptions? options = null)
            : base("supabase:supabase:Migration", name, args ?? new MigrationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Migration(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("supabase:supabase:Migration", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Migration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Migration Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Migration(name, id, options);
        }
    }

    public sealed class MigrationArgs : global::Pulumi.ResourceArgs
    {
        [Input("db_password", required: true)]
        public Input<string> Db_password { get; set; } = null!;

        [Input("include_all")]
        public Input<bool>? Include_all { get; set; }

        [Input("include_roles")]
        public Input<bool>? Include_roles { get; set; }

        [Input("include_seed")]
        public Input<bool>? Include_seed { get; set; }

        [Input("project_id", required: true)]
        public Input<string> Project_id { get; set; } = null!;

        public MigrationArgs()
        {
        }
        public static new MigrationArgs Empty => new MigrationArgs();
    }
}
