// Code generated by pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Supbase Personal Access Token for account
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "supabase:token")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "SUPABASE_ACCESS_TOKEN").(string)
}
func GetVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "supabase:version")
}
