// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/nitrictech/pulumi-supabase/sdk/v3/go/supabase/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Supbase Personal Access Token for account
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "supabase:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "SUPABASE_ACCESS_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}
func GetVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "supabase:version")
}
