// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function applyMigrations(args: ApplyMigrationsArgs, opts?: pulumi.InvokeOptions): Promise<ApplyMigrationsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("supabase:projects:applyMigrations", {
        "db_host": args.db_host,
        "db_pass": args.db_pass,
        "include_all": args.include_all,
        "include_roles": args.include_roles,
        "include_seed": args.include_seed,
    }, opts);
}

export interface ApplyMigrationsArgs {
    db_host: string;
    db_pass: string;
    include_all?: boolean;
    include_roles?: boolean;
    include_seed?: boolean;
}

export interface ApplyMigrationsResult {
    readonly success: boolean;
}
export function applyMigrationsOutput(args: ApplyMigrationsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<ApplyMigrationsResult> {
    return pulumi.output(args).apply((a: any) => applyMigrations(a, opts))
}

export interface ApplyMigrationsOutputArgs {
    db_host: pulumi.Input<string>;
    db_pass: pulumi.Input<string>;
    include_all?: pulumi.Input<boolean>;
    include_roles?: pulumi.Input<boolean>;
    include_seed?: pulumi.Input<boolean>;
}
