// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'supabase:projects:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    public /*out*/ readonly anon_key!: pulumi.Output<string>;
    public readonly cloud!: pulumi.Output<string | undefined>;
    public /*out*/ readonly database_host!: pulumi.Output<string>;
    public readonly db_pass!: pulumi.Output<string>;
    public readonly kps_enabled!: pulumi.Output<boolean | undefined>;
    public readonly name!: pulumi.Output<string | undefined>;
    public readonly organization_id!: pulumi.Output<number>;
    public readonly plan!: pulumi.Output<string | undefined>;
    public /*out*/ readonly project_endpoint!: pulumi.Output<string>;
    public /*out*/ readonly project_id!: pulumi.Output<number>;
    public /*out*/ readonly project_name!: pulumi.Output<string>;
    public /*out*/ readonly project_ref!: pulumi.Output<string>;
    public readonly region!: pulumi.Output<string | undefined>;
    public /*out*/ readonly service_key!: pulumi.Output<string>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.db_pass === undefined) && !opts.urn) {
                throw new Error("Missing required property 'db_pass'");
            }
            if ((!args || args.organization_id === undefined) && !opts.urn) {
                throw new Error("Missing required property 'organization_id'");
            }
            resourceInputs["cloud"] = args ? args.cloud : undefined;
            resourceInputs["db_pass"] = args?.db_pass ? pulumi.secret(args.db_pass) : undefined;
            resourceInputs["kps_enabled"] = args ? args.kps_enabled : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["organization_id"] = args ? args.organization_id : undefined;
            resourceInputs["plan"] = args ? args.plan : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["anon_key"] = undefined /*out*/;
            resourceInputs["database_host"] = undefined /*out*/;
            resourceInputs["project_endpoint"] = undefined /*out*/;
            resourceInputs["project_id"] = undefined /*out*/;
            resourceInputs["project_name"] = undefined /*out*/;
            resourceInputs["project_ref"] = undefined /*out*/;
            resourceInputs["service_key"] = undefined /*out*/;
        } else {
            resourceInputs["anon_key"] = undefined /*out*/;
            resourceInputs["cloud"] = undefined /*out*/;
            resourceInputs["database_host"] = undefined /*out*/;
            resourceInputs["db_pass"] = undefined /*out*/;
            resourceInputs["kps_enabled"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["organization_id"] = undefined /*out*/;
            resourceInputs["plan"] = undefined /*out*/;
            resourceInputs["project_endpoint"] = undefined /*out*/;
            resourceInputs["project_id"] = undefined /*out*/;
            resourceInputs["project_name"] = undefined /*out*/;
            resourceInputs["project_ref"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["service_key"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["anon_key", "db_pass", "service_key"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Project.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    cloud?: pulumi.Input<string>;
    db_pass: pulumi.Input<string>;
    kps_enabled?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    organization_id: pulumi.Input<number>;
    plan?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
}
