name: Production Release
on:
  push:
    branches:
      - main
    paths:
      - 'provider/**'
      - 'sdk/**'

jobs:
  # Bump the membrane version
  version_bump:
    name: Bump Version & Push Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          # Use GITHUB_TOKEN here to prevent further workflows
          # generated on 'tag' action
          github_token: ${{ secrets.NITRIC_BOT_TOKEN }}